<?php

/**
 * @file
 * Contains example_fieldtype.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function example_fieldtype_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the example_fieldtype module.
    case 'help.page.example_fieldtype':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is for adding field type in entity type') . '</p>';
      return $output;

    default:
  }
}
