<?php

/**
 * @file
 * Contains config_impoter_entity.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function config_impoter_entity_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the config_impoter_entity module.
    case 'help.page.config_impoter_entity':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is for json file impoter') . '</p>';
      return $output;

    default:
  }
}
