<?php

/**
 * @file
 * Contains example_fieldwidget.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function example_fieldwidget_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the example_fieldwidget module.
    case 'help.page.example_fieldwidget':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is for field widget') . '</p>';
      return $output;

    default:
  }
}
