<?php

/**
  * Implements hook_theme()
  */
function javascript_accordion_theme(){
  return [
    'javascript-example'=> [
        'variables' => [
            'title' => NULL,
        ],
    ], 
  ];
}


//   function gq_theme($existing, $type, $theme, $path) {
//     return array(
//        'gq_form' => array(
//          'variables' => array(
//            'first_name_field' => $form['field_first_name'],
//          ),
//        ),
//      );
//    }