<?php

/**
 * @file
 * Contains productentity.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function productentity_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the productentity module.
    case 'help.page.productentity':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is module for content entity type creation') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function productentity_theme() {
  $theme = [];
  $theme['products'] = [
    'render element' => 'elements',
    'file' => 'products.page.inc',
    'template' => 'products',
  ];
  $theme['products_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'products.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function productentity_theme_suggestions_products(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#products'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'products__' . $sanitized_view_mode;
  $suggestions[] = 'products__' . $entity->bundle();
  $suggestions[] = 'products__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'products__' . $entity->id();
  $suggestions[] = 'products__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
